### ISSUE TITLE
Document format of subscription error responses

### ISSUE THREAD

**Issue by 6a68** [mozilla/subhub#148]
Please document the possible set of error codes returned when a subscription fails.

Based on #81, it appears that the stripe error info is directly passed through, but given that subhub is a payment abstraction layer, I could see this changing over time.

This could simply be added to the openAPI yaml as an [enum](https://swagger.io/docs/specification/2-0/enums/) of possible values, and we could generate documentation from there.

**Comment by marty331** [comment]
@bbangert I chatted with 6a68 and he asked me to get info from you on this. - I'm just wanting to gather more info on what it is you are looking for here?  I've already addressed that we would not provide detailed failure messages in https://github.com/mozilla/subhub/issues/98 but I wanted to see if this was something different.

**Comment by bbangert** [comment]
I believe this was to have the swagger.yaml fully represent the API. Right now for example this method only lists a 200, which implies there's no other response it can possibly return:
https://github.com/mozilla/subhub/blob/master/src/sub/swagger.yaml#L55

Is that correct? Or could it return a 400 or 404?

Most of the methods now have all the error responses, but a few don't. This issue was mainly about ensuring they all document every response the method might return.

**Comment by bbangert** [comment]
After looking at it again, maybe it can only return a 200. If that's the case since those are ops type routes, this issue might have been resolved already by the other methods having all the responses doc'd.

**Comment by stlhood** [comment]
Closing per Ben's recommendation.
