### ISSUE TITLE
Remove Firefox Route

### ISSUE THREAD

**Issue by marty331** [mozilla/subhub#210]
Should not be sent to Firefox, per @bbangert 

https://github.com/mozilla/subhub/blob/master/subhub/hub/stripe/customer.py#L216

**Comment by bbangert** [comment]
It might be good to clarify exactly what's going on here. Cause I've stared at this for an hour or more working on the states in my head and I'm not entirely clear about this and the event below, and why other permutations are dropped.

Firefox Accounts only needs to know about whether a subscription should be turned on, or off. This means it should know when a subscription is active, and when it isn't. But the block here is about subscription updates... and while a subscription may be set to cancel at the period end, FxA doesn't care and shouldn't get that event at all. 

Per [Stripe documentation on cancellation events](https://stripe.com/docs/billing/subscriptions/canceling-pausing#events), no matter what states a subscription goes through, when its over, a subscription delete is sent, so that should definitely result in an event being sent to deactivate the subscription.

The only other case that could result in a subscription being deactivated *before* a subscription delete event occurs is if a subscription is allowed to move to `past_due`, `incomplete`, or `unpaid`. I'm not sure what we should do in these cases, but the code at the moment sort of considers anything that isn't `active` during a subscription update to not even warrant a notification to any other system.

So to be clear, as far as I can tell this is the current behavior of subhub:
 
- Sub Update: Status changes to `past_due`, *no event is sent*.
- Sub Update: Status changes to `trialing` (Maybe Support gave someone more trial time on a `past_due` subscription), *no event is sent*
- Sub Update: Status doesn't change, but `cancel_at_period_end` is set, **event is sent** (even though FxA doesn't need it, that's what this ticket was filed for!)
- Sub Update: Status is not `active` and `cancel_at_period_end` is set, *no event is sent*

Given that the account should be considered active if they're trialing or active, it seems like the second block referenced above should trigger if the status is `active` or `trialing`.

**Comment by marty331** [comment]
If removing from Firefox route, we should remove the FxA required fields.

**Comment by marty331** [comment]
@bbangert Working on changes to this now.  Will only send data to FxA if Subscription is created or deleted.  Other events that were referencing FxA are bring removed.

**Comment by marty331** [comment]
Included in PR #222
