### ISSUE TITLE
Need more details about card_declined errors

### ISSUE THREAD

**Issue by lmorchard** [mozilla/subhub#98]
Since Issue #70 and then PR #81, I'm seeing `code` and `message` added to errors relayed from Stripe. 

I think we'll also need more things like `type` and `decline_code` if available. We can display the `message` for now, but we will need the more abstract codes to select localized messages when we eventually add more locales than en-US.

**Comment by jackiemunroe** [comment]
@lmorchard the problem here is that the information that you are requesting is provided to Stripe by the card issuer. Stripe even states that in most cases declines are categorized as generic by the issuers, so I don't think that we should create a system that relies on data that is not guaranteed. Also, from a security standpoint, we probably don't want to tell users why their card was declined, just that it was.

**Comment by lmorchard** [comment]
Just for the sake of completeness, here's a list of error messages we have in terms of copy:

https://docs.google.com/spreadsheets/d/1Kl2v8hJTntQvtGUTJcvWpSZQLIVvoYgnRboT2Lziu_w/edit?disco=AAAADAewemI&usp_dm=false&ts=5cdc2bc0#gid=0

**Comment by marty331** [comment]
After discussion we have decided to not implement this.  Product owners for Subhub and FxA will discuss details.
